# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-07-02 15:26:16
"""
import arcpy
import os

def FeatureClassGenerator(workspace, wild_card, feature_type, recursive) :
  with arcpy.EnvManager(workspace = workspace):

    dataset_list = [""]
    if recursive:
      datasets = arcpy.ListDatasets()
      dataset_list.extend(datasets)

    for dataset in dataset_list:
      featureclasses = arcpy.ListFeatureClasses(wild_card, feature_type, dataset)
      for fc in featureclasses:
        yield os.path.join(workspace, dataset, fc), fc


def Model1():  # Model1

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True

    Monthly_Vessel_Tracks_gdb = "E:\\ArcGIS\\Projects\\AIS\\processing\\Monthly_Vessel_Tracks.gdb"

    for US_Vessel_Traffic_2016_01, Name in FeatureClassGenerator(Monthly_Vessel_Tracks_gdb, "", "LINE", "NOT_RECURSIVE"):

        # Process: Copy Features (Copy Features) (management)
        Name = "US_Vessel_Traffic_2016_01"
        _Name_gen = fr"E:\ArcGIS\Projects\AIS\processing\Monthly_Vessel_Tracks.gdb\{Name}_gen"
        arcpy.management.CopyFeatures(in_features=US_Vessel_Traffic_2016_01, out_feature_class=_Name_gen)

        # Process: Generalize (Generalize) (edit)
        US_Vessel_Traffic_2016_01_2_ = arcpy.edit.Generalize(in_features=_Name_gen, tolerance="500 Meters")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(parallelProcessingFactor="90%", retryOnFailures=2, scratchWorkspace="E:\\ArcGIS\\Projects\\AIS\\AIS.gdb", 
                          workspace="E:\\ArcGIS\\Projects\\AIS\\AIS.gdb"):
        Model1()
