md_credits = "NOAA, BOEM, USCG, Marine Cadastre, Esri"
md_description = "Monthly AIS Vessel Traffic Hexbin Summaries including total monthly track counts (for all vessels) and individual breakouts for each of the nine vessel groups: cargo, fishing, military, not available, other, passenger, pleasure, tanker, and tow."
# md_summary = "Monthly AIS Vessel Traffic Hexbin Summaries for"
md_tags = "AIS, vessel traffic, U.S. Vessel Traffic, marine spatial planning, oceans, marine, esri_oceans, esri_environment, law_hosted"
md_useLimitations = "These are use limitations"